### ISSUE TITLE
Zero Division error 

### ISSUE THREAD

**Issue by MopishFungus** [Glastis/Flipper-Zero-music-converter#1]
I downloaded everything fresh and new.  New python 3.9 install and I installed mido for everything to work. I got my midi file and dragged it in and I get this error
[https://ibb.co/ZHy1Smy]

Traceback (most recent call last):
  File "C:\Users\Jacob\Desktop\Flipper-Zero-music-converter-master\midi2fmf.py", line 75, in <module>
    main()
  File "C:\Users\Jacob\Desktop\Flipper-Zero-music-converter-master\midi2fmf.py", line 72, in main
    convert_file(file_name, output_file_name, bpm)
  File "C:\Users\Jacob\Desktop\Flipper-Zero-music-converter-master\midi2fmf.py", line 39, in convert_file
    pause = str(round(3 / msg_dict["time"]))
ZeroDivisionError: division by [zero](url)

**Comment by MopishFungus** [comment]
I apologize for closing and reponing i pressed the wrong button but still need assistance

**Comment by Glastis** [comment]
Hi,

Can you provide me the midi file you were using, in a pastebin or else?
I need it to do some tests on my own.

**Comment by MopishFungus** [comment]
i was gonna use this one
https://www.mediafire.com/file/enku9yn6emm9ltb/Indian+Funny.mid/file

**Comment by Glastis** [comment]
I committed a modification that should fix this problem. However, I currently do not have my flipper to test it out, but I can test it in few days.

**Comment by MopishFungus** [comment]
I don't have the zero division error so that is fixed except the fmf in the flipper doesn't play right. I tried another midi and it crashed on my flipper.

**Comment by Glastis** [comment]
You're right, the script I used to make this tool seems to have problems with most songs. I'll investigate on this soon.
